<?php

namespace AppBundle\Entity;

/**
 * LessonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LessonRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllArray()
    {
        return $this->createQueryBuilder('l')
            ->getQuery()
            ->getArrayResult();

    }
}
